name: Best pipeline in the world
on:
  push:
    branches:
      - main

jobs:
  push-to-acr:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main
      - name: login to acr
        uses: azure/docker-login@v1
        with:
          login-server: ankurcontainerregistry.azurecr.io
          username: ankurcontainerregistry
          password: WEoyZNhSNqfa/D/nj9V90n0mr3Oau6NmYkvtKT4roa+ACRCy5tpu
      - name: build and push image
        run: mvn compile jib:build